// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_get_permit_freq_info
List cpp_get_permit_freq_info(String fn);
RcppExport SEXP _alevinQC_cpp_get_permit_freq_info(SEXP fnSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type fn(fnSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_get_permit_freq_info(fn));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_alevinQC_cpp_get_permit_freq_info", (DL_FUNC) &_alevinQC_cpp_get_permit_freq_info, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_alevinQC(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
